# Generated by Django 6.0.3 on 2026-04-14 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('lookups', '0003_journaltag'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_immutable', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='events.event')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookups.mood')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='lookups.journaltag')),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-entry_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='journal.journalentry')),
            ],
            options={
                'db_table': 'reflections',
                'ordering': ['created_timestamp'],
            },
        ),
    ]
