# Generated by Django 6.0.3 on 2026-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_trust_score_contact_is_active'),
        ('lookups', '0007_alter_factcategory_user_alter_factcategory_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPersonalDetail',
            new_name='Fact',
        ),
    ]
