# Generated by Django 6.0.3 on 2026-05-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_contactpersonaldetail_fact'),
        ('lookups', '0007_alter_factcategory_user_alter_factcategory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='lookups.factcategory'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='contacts.contact'),
        ),
        migrations.AlterModelTable(
            name='fact',
            table='facts',
        ),
    ]
