# Generated by Django 6.0.3 on 2026-05-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_fact_category_alter_fact_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['id']},
        ),
    ]
