# Generated by Django 6.0.3 on 2026-05-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_fact_options'),
        ('lookups', '0009_alter_entrytag_user_alter_entrytag_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactLooseNote',
            new_name='Observation',
        ),
    ]
