# Generated by Django 6.0.3 on 2026-05-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_contactloosenote_observation'),
        ('lookups', '0009_alter_entrytag_user_alter_entrytag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='lookups.observationmarker'),
        ),
        migrations.AlterModelTable(
            name='observation',
            table='observations',
        ),
    ]
