# Generated by Django 6.0.3 on 2026-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_observation_contact_alter_observation_marker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='connection_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='interaction_diversity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='interaction_frequency_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship_trend',
            field=models.CharField(choices=[('growing', 'Growing'), ('stable', 'Stable'), ('fading', 'Fading'), ('dormant', 'Dormant')], default='dormant', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='sentiment_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
