# Generated by Django 6.0.3 on 2026-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_connection_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='closeness_score',
        ),
    ]
