# Generated by Django 6.0.3 on 2026-05-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_profile_picture'),
        ('lookups', '0013_seed_default_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='lookups.relation'),
        ),
    ]
