# Generated by Django 6.0.3 on 2026-07-10 05:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_observation_status(apps, schema_editor):
    Observation = apps.get_model('contacts', 'Observation')
    Observation.objects.filter(is_active=True).update(status='current')
    Observation.objects.filter(is_active=False).update(status='archived')


def reverse_observation_status_backfill(apps, schema_editor):
    Observation = apps.get_model('contacts', 'Observation')
    Observation.objects.filter(status='archived').update(is_active=False)
    Observation.objects.exclude(status='archived').update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_relation'),
        ('events', '0004_event_timeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='events.event'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('conversation_cue', 'Conversation cue'), ('appreciation', 'Appreciation'), ('change', 'Change')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('revisit_later', 'Revisit later'), ('archived', 'Archived')], default='current', max_length=20),
        ),
        migrations.RunPython(
            backfill_observation_status,
            reverse_observation_status_backfill,
        ),
    ]
