# Generated by Django 6.0.3 on 2026-07-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_observation_context_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='is_conversation_cue',
            field=models.BooleanField(default=False),
        ),
    ]
