# Generated by Django 6.0.3 on 2026-07-10 23:28

from django.db import migrations, models


def split_legacy_fact_labels(apps, schema_editor):
    Fact = apps.get_model('contacts', 'Fact')

    for fact in Fact.objects.filter(label__isnull=True).iterator():
        value = fact.detail_value.strip()
        if value.count(':') != 1 or ': ' not in value or '\n' in value:
            continue

        label, detail_value = (part.strip() for part in value.split(':', 1))
        if not label or not detail_value or len(label) > 120:
            continue

        Fact.objects.filter(pk=fact.pk, label__isnull=True).update(
            label=label,
            detail_value=detail_value,
        )


def restore_legacy_fact_values(apps, schema_editor):
    Fact = apps.get_model('contacts', 'Fact')

    for fact in Fact.objects.exclude(label__isnull=True).iterator():
        Fact.objects.filter(pk=fact.pk).update(
            detail_value=f'{fact.label}: {fact.detail_value}',
            label=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_fact_conversation_cue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(
            split_legacy_fact_labels,
            restore_legacy_fact_values,
        ),
    ]
