# Generated by Django 6.0.3 on 2026-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_fact_label'),
        ('events', '0004_event_timeline_fields'),
        ('lookups', '0017_contextcategory_uniq_context_category_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['contact', '-pinned_at'], name='fact_contact_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['contact', '-pinned_at'], name='obs_contact_pinned_idx'),
        ),
    ]
