# Generated by Django 6.0.3 on 2026-07-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_fact_pinned_at_observation_pinned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender_identity',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='met_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='met_through',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ContactEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_education',
                'ordering': ['-is_current', '-start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_employment',
                'ordering': ['-is_current', '-start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_addresses',
                'ordering': ['-is_primary', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='unique_primary_contact_address')],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('value', models.CharField(max_length=320)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_methods',
                'ordering': ['kind', '-is_primary', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact', 'kind'), name='unique_primary_contact_method_kind')],
            },
        ),
    ]
