# Generated by Django 6.0.3 on 2026-07-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_contact_gender_identity_contact_met_location_and_more'),
        ('events', '0004_event_timeline_fields'),
        ('journals', '0005_carryforwardfactdraft_carryforwardobservationdraft_and_more'),
        ('lookups', '0018_emotionstate_episodecategory_episodecharacteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='source_item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='source_reflection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_facts', to='journals.reflection'),
        ),
        migrations.AddField(
            model_name='observation',
            name='source_item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='source_reflection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_observations', to='journals.reflection'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reflection__isnull', False)), fields=('source_reflection', 'source_item_id'), name='unique_fact_reflection_source'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reflection__isnull', False)), fields=('source_reflection', 'source_item_id'), name='unique_observation_reflection_source'),
        ),
    ]
