# Generated by Django 6.0.3 on 2026-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_user_id_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tier',
            field=models.CharField(choices=[('routine', 'Routine'), ('milestone', 'Milestone')], default='routine', max_length=20),
        ),
    ]
