# Generated by Django 6.0.3 on 2026-07-19 11:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_fact_source_item_id_fact_source_reflection_and_more'),
        ('events', '0004_event_timeline_fields'),
        ('media', '0002_media_verification_and_upload_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField()),
                ('start_timestamp', models.DateTimeField(blank=True, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('inherits_event_participants', models.BooleanField(default=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='events.event')),
            ],
            options={
                'db_table': 'event_chapters',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventChapterParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='events.eventchapter')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_chapter_participations', to='contacts.contact')),
            ],
            options={
                'db_table': 'event_chapter_participants',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('decorative', models.BooleanField(default=False)),
                ('is_cover', models.BooleanField(default=False)),
                ('focal_x', models.DecimalField(decimal_places=5, default=Decimal('0.50000'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('focal_y', models.DecimalField(decimal_places=5, default=Decimal('0.50000'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='media_attachments', to='events.eventchapter')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='events.event')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_attachments', to='media.mediaasset')),
            ],
            options={
                'db_table': 'event_media',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventMediaCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_kind', models.CharField(choices=[('event_cover', 'Event cover'), ('chapter_carousel', 'Chapter carousel')], max_length=32)),
                ('x', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('y', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('width', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00001')), django.core.validators.MaxValueValidator(1)])),
                ('height', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00001')), django.core.validators.MaxValueValidator(1)])),
                ('source_orientation_revision', models.PositiveIntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('event_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='events.eventmedia')),
            ],
            options={
                'db_table': 'event_media_crops',
                'ordering': ['crop_kind', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='eventchapter',
            index=models.Index(fields=['event', 'position', 'id'], name='event_chapter_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventchapter',
            constraint=models.UniqueConstraint(fields=('event', 'position'), name='unique_event_chapter_position'),
        ),
        migrations.AddConstraint(
            model_name='eventchapter',
            constraint=models.CheckConstraint(condition=models.Q(('start_timestamp__isnull', True), ('end_timestamp__isnull', True), ('end_timestamp__gte', models.F('start_timestamp')), _connector='OR'), name='event_chapter_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='eventchapterparticipant',
            constraint=models.UniqueConstraint(fields=('chapter', 'contact'), name='unique_event_chapter_contact'),
        ),
        migrations.AddConstraint(
            model_name='eventchapterparticipant',
            constraint=models.UniqueConstraint(fields=('chapter', 'display_order'), name='unique_event_chapter_contact_order'),
        ),
        migrations.AddIndex(
            model_name='eventmedia',
            index=models.Index(fields=['event', 'chapter', 'display_order'], name='event_media_scope_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', True)), fields=('event', 'media_asset'), name='unique_whole_event_media_asset'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', False)), fields=('chapter', 'media_asset'), name='unique_chapter_media_asset'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', True)), fields=('event', 'display_order'), name='unique_whole_event_media_order'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', False)), fields=('chapter', 'display_order'), name='unique_chapter_media_order'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', True), ('is_cover', True)), fields=('event',), name='unique_whole_event_media_cover'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', False), ('is_cover', True)), fields=('chapter',), name='unique_chapter_media_cover'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.CheckConstraint(condition=models.Q(('focal_x__gte', 0), ('focal_x__lte', 1)), name='event_media_focal_x_normalized'),
        ),
        migrations.AddConstraint(
            model_name='eventmedia',
            constraint=models.CheckConstraint(condition=models.Q(('focal_y__gte', 0), ('focal_y__lte', 1)), name='event_media_focal_y_normalized'),
        ),
        migrations.AddConstraint(
            model_name='eventmediacrop',
            constraint=models.UniqueConstraint(fields=('event_media', 'crop_kind'), name='unique_event_media_crop_kind'),
        ),
        migrations.AddConstraint(
            model_name='eventmediacrop',
            constraint=models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1)), name='event_media_crop_x_normalized'),
        ),
        migrations.AddConstraint(
            model_name='eventmediacrop',
            constraint=models.CheckConstraint(condition=models.Q(('y__gte', 0), ('y__lte', 1)), name='event_media_crop_y_normalized'),
        ),
        migrations.AddConstraint(
            model_name='eventmediacrop',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('width__lte', 1)), name='event_media_crop_width_normalized'),
        ),
        migrations.AddConstraint(
            model_name='eventmediacrop',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('height__lte', 1)), name='event_media_crop_height_normalized'),
        ),
    ]
