RELATIONSHIP_TREND_GROWING = 'growing'
RELATIONSHIP_TREND_STABLE = 'stable'
RELATIONSHIP_TREND_FADING = 'fading'
RELATIONSHIP_TREND_DORMANT = 'dormant'

RELATIONSHIP_TREND_CHOICES = [
    (RELATIONSHIP_TREND_GROWING, 'Growing'),
    (RELATIONSHIP_TREND_STABLE, 'Stable'),
    (RELATIONSHIP_TREND_FADING, 'Fading'),
    (RELATIONSHIP_TREND_DORMANT, 'Dormant'),
]

INTERACTION_FREQUENCY_BUCKETS = [
    (14, 3),
    (30, 2),
    (90, 1),
]
INTERACTION_FREQUENCY_MULTIPLIER = 10
MAX_RELATIONSHIP_SCORE = 100

RELATIONSHIP_TREND_SCORES = {
    RELATIONSHIP_TREND_GROWING: 100,
    RELATIONSHIP_TREND_STABLE: 70,
    RELATIONSHIP_TREND_FADING: 35,
    RELATIONSHIP_TREND_DORMANT: 0,
}

CONNECTION_STRENGTH_WEIGHTS = {
    'interaction_frequency_score': 0.25,
    'relationship_trend': 0.25,
    'interaction_diversity_score': 0.25,
    'sentiment_profile': 0.25,
}

MOOD_POLARITY_POSITIVE = 1
MOOD_POLARITY_NEUTRAL = 0
MOOD_POLARITY_NEGATIVE = -1

MOOD_POLARITY_CHOICES = [
    (MOOD_POLARITY_POSITIVE, 'Positive'),
    (MOOD_POLARITY_NEUTRAL, 'Neutral'),
    (MOOD_POLARITY_NEGATIVE, 'Negative'),
]
