# Generated by Django 6.0.3 on 2026-05-02 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_trust_score_contact_is_active'),
        ('lookups', '0003_journaltag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteMarker',
            new_name='ObservationMarker',
        ),
    ]
