# Generated by Django 6.0.3 on 2026-05-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_rename_notemarker_observationmarker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmarker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_markers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='observationmarker',
            table='observation_markers',
        ),
    ]
