# Generated by Django 6.0.3 on 2026-05-02 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0007_alter_factcategory_user_alter_factcategory_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalTag',
            new_name='EntryTag',
        ),
    ]
