# Generated by Django 6.0.3 on 2026-05-02 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0008_rename_journaltag_entrytag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='entrytag',
            table='entry_tags',
        ),
    ]
