# Generated by Django 6.0.3 on 2026-05-02 16:49

from django.db import migrations, models


def set_default_mood_polarities(apps, schema_editor):
    Mood = apps.get_model('lookups', 'Mood')
    polarity_by_name = {
        'Happy': 1,
        'Neutral': 0,
        'Sad': -1,
        'Angry': -1,
    }
    for name, polarity in polarity_by_name.items():
        Mood.objects.filter(name=name, is_system_default=True).update(
            polarity=polarity
        )


def reset_default_mood_polarities(apps, schema_editor):
    Mood = apps.get_model('lookups', 'Mood')
    Mood.objects.filter(
        name__in=['Happy', 'Neutral', 'Sad', 'Angry'],
        is_system_default=True,
    ).update(polarity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0009_alter_entrytag_user_alter_entrytag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='polarity',
            field=models.IntegerField(choices=[(1, 'Positive'), (0, 'Neutral'), (-1, 'Negative')], default=0),
        ),
        migrations.RunPython(
            set_default_mood_polarities,
            reset_default_mood_polarities,
        ),
    ]
