# Generated by Django 6.0.3 on 2026-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_contact_closeness_score'),
        ('lookups', '0010_mood_polarity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosenessScore',
        ),
    ]
