# Generated by Django 6.0.3 on 2026-05-03 22:30

from django.db import migrations


def seed_default_relations(apps, schema_editor):
    Relation = apps.get_model('lookups', 'Relation')
    relation_names = [
        'Friend',
        'Family',
        'Coworker',
        'Mentor',
        'Acquaintance',
        'Romantic Partner',
        'Neighbor',
        'Classmate',
    ]
    for name in relation_names:
        Relation.objects.get_or_create(
            name=name,
            user=None,
            defaults={'is_system_default': True},
        )


def reverse_seed_default_relations(apps, schema_editor):
    Relation = apps.get_model('lookups', 'Relation')
    Relation.objects.filter(is_system_default=True, user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0012_relation'),
    ]

    operations = [
        migrations.RunPython(
            seed_default_relations,
            reverse_seed_default_relations,
        ),
    ]
