# Generated by Django 6.0.3 on 2026-06-22 16:52

from django.db import migrations
from django.db.models import Count

def dedupe_context_categories(apps, schema_editor):
    ContextCategory = apps.get_model("lookups", "ContextCategory")
    Event = apps.get_model("events","Event")

    duplicate_names = (
        ContextCategory.objects
        .filter(is_system_default=True, user__isnull=True)
        .values("name")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for row in duplicate_names:
        categories = list(
            ContextCategory.objects
            .filter(
                name=row["name"],
                is_system_default=True,
                user__isnull=True,
            )
            .order_by("id")
        )

        canonical = categories[0]
        duplicates = categories[1:]

        for duplicate in duplicates:
            Event.objects.filter(context_category_id=duplicate.id).update(
                context_category_id=canonical.id
            )
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0014_interactionmode'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_context_categories, migrations.RunPython.noop)
    ]
