# Generated by Django 6.0.3 on 2026-06-22 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0015_dedupe_context_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contextcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('name',), name='uniq_context_category_system_default_name'),
        ),
    ]
