# Generated by Django 6.0.3 on 2026-07-17 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


JOURNAL_LOOKUP_SEEDS = {
    'EpisodeCategory': [
        ('thought_pattern', 'Thought pattern', 'heart-pulse', '#f3c4d4'),
        ('stress_response', 'Stress response', 'activity', '#d8cdf7'),
        ('sensory_overload', 'Sensory overload', 'waves', '#c9dcf6'),
        ('energy_state', 'Energy state', 'battery', '#d8ead9'),
    ],
    'EpisodeCharacteristic': [
        ('looping_thoughts', 'Looping thoughts', 'repeat', '#ddd2fb'),
        ('difficulty_focusing', 'Difficulty focusing', 'focus', '#ddd2fb'),
        ('restless', 'Restless', 'activity', '#ddd2fb'),
        ('racing_thoughts', 'Racing thoughts', 'wind', '#ddd2fb'),
        ('physical_tension', 'Physical tension', 'body', '#ddd2fb'),
        ('avoidance', 'Avoidance', 'corner-down-left', '#ddd2fb'),
    ],
    'EpisodeContextTag': [
        ('stressful_conversation', 'Stressful conversation', 'messages-square', '#ddd2fb'),
        ('poor_sleep', 'Poor sleep', 'moon', '#ddd2fb'),
        ('work_pressure', 'Work pressure', 'briefcase', '#ddd2fb'),
        ('social_overload', 'Social overload', 'users', '#ddd2fb'),
    ],
    'SocialEnergyFactor': [
        ('long_conversation', 'Long conversation', 'messages-square', '#ddd2fb'),
        ('comfortable_setting', 'Comfortable setting', 'armchair', '#ddd2fb'),
        ('large_group', 'Large group', 'users', '#ddd2fb'),
        ('unfamiliar_people', 'Unfamiliar people', 'user-round-question', '#ddd2fb'),
        ('conflict', 'Conflict', 'message-circle-warning', '#ddd2fb'),
        ('poor_sleep', 'Poor sleep', 'moon', '#ddd2fb'),
    ],
    'EmotionState': [
        ('positive', 'Positive', 'smile', '#b9e7ce'),
        ('neutral', 'Neutral', 'meh', '#d9dde5'),
        ('negative', 'Negative', 'frown', '#f4c1d2'),
        ('very_negative', 'Very negative', 'frown', '#efafc3'),
        ('hurt', 'Hurt', 'heart-crack', '#ddd2fb'),
        ('anxious', 'Anxious', 'circle-alert', '#ddd2fb'),
        ('disconnected', 'Disconnected', 'unlink', '#ddd2fb'),
        ('unsteady', 'Unsteady', 'waves', '#ddd2fb'),
        ('angry', 'Angry', 'flame', '#f5c4c4'),
        ('confused', 'Confused', 'circle-help', '#d7e1f4'),
        ('ashamed', 'Ashamed', 'eye-off', '#ead6df'),
        ('calm', 'Calm', 'leaf', '#c9ead7'),
        ('hopeful', 'Hopeful', 'sun', '#f5e5ad'),
    ],
    'InteractionDynamic': [
        ('felt_dismissed', 'Felt dismissed', 'message-circle-x', '#ddd2fb'),
        ('uneven_engagement', 'Uneven engagement', 'scale', '#ddd2fb'),
        ('guarded', 'Guarded', 'shield', '#ddd2fb'),
        ('supported', 'Supported', 'heart-handshake', '#c9ead7'),
        ('mutual_engagement', 'Mutual engagement', 'messages-square', '#c9ead7'),
        ('misunderstood', 'Misunderstood', 'message-circle-warning', '#f4c1d2'),
    ],
}


def seed_journal_lookups(apps, schema_editor):
    for model_name, rows in JOURNAL_LOOKUP_SEEDS.items():
        model = apps.get_model('lookups', model_name)
        for code, name, icon_reference, color in rows:
            model.objects.update_or_create(
                code=code,
                is_system_default=True,
                defaults={
                    'user': None,
                    'name': name,
                    'icon_reference': icon_reference,
                    'color': color,
                },
            )


def unseed_journal_lookups(apps, schema_editor):
    for model_name, rows in JOURNAL_LOOKUP_SEEDS.items():
        model = apps.get_model('lookups', model_name)
        model.objects.filter(
            is_system_default=True,
            code__in=[row[0] for row in rows],
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0017_contextcategory_uniq_context_category_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emotion_states',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_emotionstate_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_emotionstate_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_emotionstate_unique_user_name')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'episode_categories',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_episodecategory_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_episodecategory_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_episodecategory_unique_user_name')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'episode_characteristics',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_episodecharacteristic_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_episodecharacteristic_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_episodecharacteristic_unique_user_name')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeContextTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'episode_context_tags',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_episodecontexttag_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_episodecontexttag_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_episodecontexttag_unique_user_name')],
            },
        ),
        migrations.CreateModel(
            name='InteractionDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interaction_dynamics',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_interactiondynamic_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_interactiondynamic_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_interactiondynamic_unique_user_name')],
            },
        ),
        migrations.CreateModel(
            name='SocialEnergyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_system_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_energy_factors',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system_default', True), ('user__isnull', True)), models.Q(('is_system_default', False), ('user__isnull', False)), _connector='OR'), name='lookups_socialenergyfactor_valid_owner'), models.UniqueConstraint(condition=models.Q(('is_system_default', True)), fields=('code',), name='lookups_socialenergyfactor_unique_system_code'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='lookups_socialenergyfactor_unique_user_name')],
            },
        ),
        migrations.RunPython(
            seed_journal_lookups,
            unseed_journal_lookups,
        ),
    ]
