"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'django_extensions',
    'storages',
    # Local apps
    'users',
    'contacts',
    'events',
    'journals',
    'media',
    'dashboard',
    'lookups',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = BASE_DIR / 'mediafiles'


def _csv_setting(name, default):
    return tuple(
        value.strip().lower()
        for value in config(name, default=default).split(',')
        if value.strip()
    )


MEDIA_ALLOWED_IMAGE_MIME_TYPES = _csv_setting(
    'MEDIA_ALLOWED_IMAGE_MIME_TYPES',
    'image/jpeg,image/png,image/webp',
)
MEDIA_ALLOWED_VIDEO_MIME_TYPES = _csv_setting(
    'MEDIA_ALLOWED_VIDEO_MIME_TYPES',
    'video/mp4,video/quicktime,video/webm',
)
MEDIA_ALLOWED_AUDIO_MIME_TYPES = _csv_setting(
    'MEDIA_ALLOWED_AUDIO_MIME_TYPES',
    'audio/mpeg,audio/mp4,audio/aac,audio/ogg,audio/wav',
)
MEDIA_IMAGE_MAX_BYTES = config(
    'MEDIA_IMAGE_MAX_BYTES',
    default=20 * 1024 * 1024,
    cast=int,
)
MEDIA_VIDEO_MAX_BYTES = config(
    'MEDIA_VIDEO_MAX_BYTES',
    default=250 * 1024 * 1024,
    cast=int,
)
MEDIA_UPLOAD_REQUEST_MAX_BYTES = config(
    'MEDIA_UPLOAD_REQUEST_MAX_BYTES',
    default=251 * 1024 * 1024,
    cast=int,
)
MEDIA_AUDIO_MAX_BYTES = config(
    'MEDIA_AUDIO_MAX_BYTES',
    default=50 * 1024 * 1024,
    cast=int,
)
MEDIA_IMAGE_MAX_PIXELS = config(
    'MEDIA_IMAGE_MAX_PIXELS',
    default=40_000_000,
    cast=int,
)
MEDIA_IMAGE_MAX_EDGE = config(
    'MEDIA_IMAGE_MAX_EDGE',
    default=12_000,
    cast=int,
)
MEDIA_CHAPTER_MAX_ASSETS = config(
    'MEDIA_CHAPTER_MAX_ASSETS',
    default=12,
    cast=int,
)
MEDIA_EVENT_MAX_ASSETS = config(
    'MEDIA_EVENT_MAX_ASSETS',
    default=40,
    cast=int,
)
MEDIA_CHAPTER_ORIGINAL_BYTES_MAX = config(
    'MEDIA_CHAPTER_ORIGINAL_BYTES_MAX',
    default=750 * 1024 * 1024,
    cast=int,
)
MEDIA_EVENT_ORIGINAL_BYTES_MAX = config(
    'MEDIA_EVENT_ORIGINAL_BYTES_MAX',
    default=2 * 1024 * 1024 * 1024,
    cast=int,
)
MEDIA_OWNER_STORAGE_QUOTA_BYTES = config(
    'MEDIA_OWNER_STORAGE_QUOTA_BYTES',
    default=10 * 1024 * 1024 * 1024,
    cast=int,
)
# Zero leaves the generic owner asset count unlimited. Event/chapter association
# limits are enforced by their owning domain services rather than this app.
MEDIA_OWNER_MAX_ASSETS = config(
    'MEDIA_OWNER_MAX_ASSETS',
    default=0,
    cast=int,
)
MEDIA_MAX_CONCURRENT_UPLOADS = config(
    'MEDIA_MAX_CONCURRENT_UPLOADS',
    default=3,
    cast=int,
)
MEDIA_UPLOAD_SESSION_EXPIRY_SECONDS = config(
    'MEDIA_UPLOAD_SESSION_EXPIRY_SECONDS',
    default=2 * 60 * 60,
    cast=int,
)
MEDIA_DELETED_ASSET_RETENTION_SECONDS = config(
    'MEDIA_DELETED_ASSET_RETENTION_SECONDS',
    default=24 * 60 * 60,
    cast=int,
)
MEDIA_UNATTACHED_ASSET_RETENTION_SECONDS = config(
    'MEDIA_UNATTACHED_ASSET_RETENTION_SECONDS',
    default=7 * 24 * 60 * 60,
    cast=int,
)
MEDIA_CONTAINER_PROBE_BYTES = config(
    'MEDIA_CONTAINER_PROBE_BYTES',
    default=8 * 1024 * 1024,
    cast=int,
)
MEDIA_FFPROBE_BINARY = config('MEDIA_FFPROBE_BINARY', default='ffprobe')
MEDIA_FFPROBE_TIMEOUT_SECONDS = config(
    'MEDIA_FFPROBE_TIMEOUT_SECONDS',
    default=30,
    cast=int,
)
MEDIA_ALLOWED_VIDEO_CODECS = _csv_setting(
    'MEDIA_ALLOWED_VIDEO_CODECS',
    'h264,hevc,vp8,vp9,av1',
)
MEDIA_ALLOWED_AUDIO_CODECS = _csv_setting(
    'MEDIA_ALLOWED_AUDIO_CODECS',
    'aac,mp3,opus,vorbis,pcm_s16le,pcm_s24le,pcm_f32le',
)
MEDIA_VIDEO_MAX_DURATION_SECONDS = config(
    'MEDIA_VIDEO_MAX_DURATION_SECONDS',
    default=10 * 60,
    cast=int,
)
MEDIA_AUDIO_MAX_DURATION_SECONDS = config(
    'MEDIA_AUDIO_MAX_DURATION_SECONDS',
    default=60 * 60,
    cast=int,
)
MEDIA_VIDEO_MAX_WIDTH = config(
    'MEDIA_VIDEO_MAX_WIDTH',
    default=3840,
    cast=int,
)
MEDIA_VIDEO_MAX_HEIGHT = config(
    'MEDIA_VIDEO_MAX_HEIGHT',
    default=2160,
    cast=int,
)
MEDIA_CONTENT_CHUNK_SIZE = config(
    'MEDIA_CONTENT_CHUNK_SIZE',
    default=64 * 1024,
    cast=int,
)
MEDIA_NONLOCAL_URL_MAX_EXPIRY_SECONDS = config(
    'MEDIA_NONLOCAL_URL_MAX_EXPIRY_SECONDS',
    default=15 * 60,
    cast=int,
)
MEDIA_CONTENT_URL_EXPIRY_SECONDS = config(
    'MEDIA_CONTENT_URL_EXPIRY_SECONDS',
    default=2 * 60 * 60,
    cast=int,
)
MEDIA_UPLOAD_SESSION_RETENTION_SECONDS = config(
    'MEDIA_UPLOAD_SESSION_RETENTION_SECONDS',
    default=7 * 24 * 60 * 60,
    cast=int,
)

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='')
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='')
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = config('AWS_QUERYSTRING_EXPIRE', default=300, cast=int)
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': config('AWS_S3_CACHE_CONTROL', default='max-age=86400'),
}

if AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'region_name': AWS_S3_REGION_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL or None,
                'custom_domain': AWS_S3_CUSTOM_DOMAIN or None,
                'querystring_auth': AWS_QUERYSTRING_AUTH,
                'querystring_expire': AWS_QUERYSTRING_EXPIRE,
                'default_acl': AWS_DEFAULT_ACL,
                'object_parameters': AWS_S3_OBJECT_PARAMETERS,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

AUTH_USER_MODEL = 'users.Users'

# TODO: Add the production frontend origin before any production deploy.
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

JWT_ACCESS_COOKIE_NAME = config('JWT_ACCESS_COOKIE_NAME', default='sj_access')
JWT_REFRESH_COOKIE_NAME = config('JWT_REFRESH_COOKIE_NAME', default='sj_refresh')
JWT_COOKIE_HTTPONLY = True
# Defaults to False in local DEBUG over HTTP, True outside DEBUG for HTTPS deployments.
JWT_COOKIE_SECURE = config('JWT_COOKIE_SECURE', default=not DEBUG, cast=bool)
JWT_COOKIE_SAMESITE = config('JWT_COOKIE_SAMESITE', default='Lax')
JWT_COOKIE_PATH = config('JWT_COOKIE_PATH', default='/')
DISABLE_MFA_REQUIREMENT = DEBUG and config(
    'DISABLE_MFA_REQUIREMENT',
    default=False,
    cast=bool,
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'URL_FORMAT_OVERRIDE': None,
}

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend', #this is a fallback
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES':    ('Bearer',),
}
