# Generated by Django 6.0.3 on 2026-05-02 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_rename_user_id_event_user'),
        ('lookups', '0009_alter_entrytag_user_alter_entrytag_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'DROP TABLE IF EXISTS reflections CASCADE;',
                'DROP TABLE IF EXISTS journal_entries_tags CASCADE;',
                'DROP TABLE IF EXISTS journal_entries CASCADE;',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('subtype', models.CharField(default='standard', max_length=50)),
                ('pre_measurement', models.IntegerField()),
                ('post_measurement', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('prompt', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journals.exercise')),
            ],
            options={
                'db_table': 'exercise_steps',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subtype', models.CharField(default='standard', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='events.event')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='lookups.mood')),
                ('tags', models.ManyToManyField(blank=True, related_name='logs', to='lookups.entrytag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('subtype', models.CharField(default='standard', max_length=50)),
                ('clarity_check', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reflections',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_exercise_user_event'),
        ),
        migrations.AddConstraint(
            model_name='exercisestep',
            constraint=models.UniqueConstraint(fields=('exercise', 'display_order'), name='unique_exercise_step_order'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_log_user_event'),
        ),
        migrations.AddConstraint(
            model_name='reflection',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_reflection_user_event'),
        ),
    ]
