# Generated by Django 6.0.3 on 2026-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='Untitled Exercise', max_length=255),
        ),
        migrations.AddField(
            model_name='reflection',
            name='title',
            field=models.CharField(default='Untitled Reflection', max_length=255),
        ),
    ]
