# Generated by Django 6.0.3 on 2026-05-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_add_titles_to_reflections_and_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
