# Generated by Django 6.0.3 on 2026-05-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_journal_title_model_defaults'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_exercise_user_event',
        ),
        migrations.RemoveConstraint(
            model_name='log',
            name='unique_log_user_event',
        ),
        migrations.RemoveConstraint(
            model_name='reflection',
            name='unique_reflection_user_event',
        ),
    ]
