# Generated by Django 6.0.3 on 2026-07-17 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_journals(apps, schema_editor):
    for model_name in ('Log', 'Reflection'):
        model = apps.get_model('journals', model_name)
        for journal in model.objects.select_related('event').all().iterator():
            occurred_at = (
                journal.event.event_timestamp
                if journal.event_id
                else journal.created_timestamp
            )
            model.objects.filter(pk=journal.pk).update(
                format='legacy',
                status='completed',
                occurred_at=occurred_at,
                completed_at=journal.updated_timestamp,
                current_step='legacy',
                revision=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_contact_gender_identity_contact_met_location_and_more'),
        ('events', '0004_event_timeline_fields'),
        ('journals', '0004_remove_exercise_unique_exercise_user_event_and_more'),
        ('lookups', '0018_emotionstate_episodecategory_episodecharacteristic_and_more'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryForwardFactDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('detail_value', models.TextField()),
                ('is_conversation_cue', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'carry_forward_fact_drafts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarryForwardObservationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('observation_type', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='current', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carry_forward_observation_drafts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalManifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('thought', 'Thought'), ('body', 'Body'), ('behavior', 'Behavior')], max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'emotional_manifestations',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalReflectionDetail',
            fields=[
                ('reflection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emotional_detail', serialize=False, to='journals.reflection')),
                ('situation', models.TextField(blank=True)),
                ('connected_factors', models.TextField(blank=True)),
                ('communicating', models.TextField(blank=True)),
                ('understanding_now', models.TextField(blank=True)),
                ('additional_writing', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emotional_reflection_details',
            },
        ),
        migrations.CreateModel(
            name='EpisodeLogDetail',
            fields=[
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='episode_detail', serialize=False, to='journals.log')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'episode_log_details',
            },
        ),
        migrations.CreateModel(
            name='FreeReflectionDetail',
            fields=[
                ('reflection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='free_detail', serialize=False, to='journals.reflection')),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'free_reflection_details',
            },
        ),
        migrations.CreateModel(
            name='InteractionReflectionDetail',
            fields=[
                ('reflection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='interaction_detail', serialize=False, to='journals.reflection')),
                ('topic_or_activity', models.TextField(blank=True)),
                ('user_actions', models.TextField(blank=True)),
                ('contact_actions', models.TextField(blank=True)),
                ('contact_response', models.TextField(blank=True)),
                ('user_response', models.TextField(blank=True)),
                ('feelings_now', models.TextField(blank=True)),
                ('important_to_understand', models.TextField(blank=True)),
                ('additional_writing', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'interaction_reflection_details',
            },
        ),
        migrations.CreateModel(
            name='MomentReflectionDetail',
            fields=[
                ('reflection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moment_detail', serialize=False, to='journals.reflection')),
                ('focus_moment', models.TextField(blank=True)),
                ('what_happened', models.TextField(blank=True)),
                ('noticed_around', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('stood_out', models.TextField(blank=True)),
                ('meaning_now', models.TextField(blank=True)),
                ('remember', models.TextField(blank=True)),
                ('additional_writing', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'moment_reflection_details',
            },
        ),
        migrations.CreateModel(
            name='ReflectionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'reflection_attachments',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'reflection_contacts',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SentimentLogDetail',
            fields=[
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sentiment_detail', serialize=False, to='journals.log')),
                ('before_connection', models.CharField(blank=True, choices=[('close', 'Close'), ('neutral', 'Neutral'), ('distant', 'Distant')], max_length=20)),
                ('after_connection', models.CharField(blank=True, choices=[('close', 'Close'), ('neutral', 'Neutral'), ('distant', 'Distant')], max_length=20)),
                ('initiated_by', models.CharField(blank=True, choices=[('me', 'Me'), ('them', 'Them'), ('mutual', 'Mutual')], max_length=20)),
                ('overall_exchange', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
            ],
            options={
                'db_table': 'sentiment_log_details',
            },
        ),
        migrations.CreateModel(
            name='SocialEnergyLogDetail',
            fields=[
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social_energy_detail', serialize=False, to='journals.log')),
                ('before_state', models.CharField(blank=True, choices=[('open', 'Open'), ('neutral', 'Neutral'), ('reserved', 'Reserved'), ('depleted', 'Depleted')], max_length=20)),
                ('battery_effect', models.CharField(blank=True, choices=[('reduced', 'Reduced'), ('unchanged', 'Unchanged'), ('increased', 'Increased')], max_length=20)),
                ('mood_shift', models.CharField(blank=True, choices=[('worse', 'Worse'), ('unchanged', 'Unchanged'), ('improved', 'Improved')], max_length=20)),
                ('behavioral_effect', models.CharField(blank=True, choices=[('quieter', 'Quieter'), ('unchanged', 'Unchanged'), ('more_social', 'More social'), ('withdrew', 'Withdrew')], max_length=20)),
                ('recovery_timing', models.CharField(blank=True, choices=[('not_yet', 'Not yet'), ('right_away', 'Right away'), ('later_day', 'Later that day'), ('next_day', 'Next day')], max_length=20)),
                ('interaction_context', models.CharField(blank=True, choices=[('one_on_one', 'One-on-one'), ('small_group', 'Small group'), ('large_group', 'Large group')], max_length=20)),
                ('group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('familiarity', models.CharField(blank=True, choices=[('very_familiar', 'Very familiar'), ('familiar', 'Familiar'), ('mixed', 'Mixed'), ('unfamiliar', 'Unfamiliar')], max_length=20)),
                ('setting', models.CharField(blank=True, choices=[('structured', 'Structured'), ('unstructured', 'Unstructured')], max_length=20)),
            ],
            options={
                'db_table': 'social_energy_log_details',
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-updated_timestamp', '-created_timestamp']},
        ),
        migrations.AlterModelOptions(
            name='reflection',
            options={'ordering': ['-updated_timestamp', '-created_timestamp']},
        ),
        migrations.AddField(
            model_name='log',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='current_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='format',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('episode', 'Episode'), ('social_energy', 'Social energy'), ('sentiment', 'Sentiment')], default='legacy', max_length=30),
        ),
        migrations.AddField(
            model_name='log',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_%(class)ss', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='log',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='reflection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='current_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reflection',
            name='format',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('interaction', 'Interaction'), ('moment', 'Moment'), ('emotional', 'Emotional'), ('free', 'Free reflection')], default='legacy', max_length=30),
        ),
        migrations.AddField(
            model_name='reflection',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_%(class)ss', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reflection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='events.event'),
        ),
        migrations.AlterField(
            model_name='log',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='events.event'),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='events.event'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'status', '-updated_timestamp'], name='log_owner_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'format', '-occurred_at'], name='log_owner_format_occurred_idx'),
        ),
        migrations.AddField(
            model_name='carryforwardfactdraft',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reflection_fact_drafts', to='lookups.factcategory'),
        ),
        migrations.AddField(
            model_name='carryforwardfactdraft',
            name='published_fact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carry_draft', to='contacts.fact'),
        ),
        migrations.AddField(
            model_name='carryforwardfactdraft',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_drafts', to='journals.reflection'),
        ),
        migrations.AddField(
            model_name='carryforwardfactdraft',
            name='target_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_fact_drafts', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='carryforwardobservationdraft',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_observation_drafts', to='events.event'),
        ),
        migrations.AddField(
            model_name='carryforwardobservationdraft',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reflection_observation_drafts', to='lookups.observationmarker'),
        ),
        migrations.AddField(
            model_name='carryforwardobservationdraft',
            name='published_observation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carry_draft', to='contacts.observation'),
        ),
        migrations.AddField(
            model_name='carryforwardobservationdraft',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_drafts', to='journals.reflection'),
        ),
        migrations.AddField(
            model_name='carryforwardobservationdraft',
            name='target_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_observation_drafts', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='emotionalreflectiondetail',
            name='emotions',
            field=models.ManyToManyField(blank=True, related_name='emotional_reflections', to='lookups.emotionstate'),
        ),
        migrations.AddField(
            model_name='emotionalmanifestation',
            name='emotional_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='journals.emotionalreflectiondetail'),
        ),
        migrations.AddField(
            model_name='episodelogdetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episode_logs', to='lookups.episodecategory'),
        ),
        migrations.AddField(
            model_name='episodelogdetail',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='episode_logs', to='lookups.episodecharacteristic'),
        ),
        migrations.AddField(
            model_name='episodelogdetail',
            name='context_tags',
            field=models.ManyToManyField(blank=True, related_name='episode_logs', to='lookups.episodecontexttag'),
        ),
        migrations.AddField(
            model_name='reflectionattachment',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reflection_attachments', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='reflectionattachment',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journals.reflection'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='cover_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journals.reflectionattachment'),
        ),
        migrations.AddField(
            model_name='reflectioncontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_links', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='reflectioncontact',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='journals.reflection'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='journal_reflections', through='journals.ReflectionContact', to='contacts.contact'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'status', '-updated_timestamp'], name='refl_owner_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'format', '-occurred_at'], name='refl_owner_format_occurr_idx'),
        ),
        migrations.AddField(
            model_name='sentimentlogdetail',
            name='after_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentiment_after_logs', to='lookups.emotionstate'),
        ),
        migrations.AddField(
            model_name='sentimentlogdetail',
            name='before_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentiment_before_logs', to='lookups.emotionstate'),
        ),
        migrations.AddField(
            model_name='sentimentlogdetail',
            name='dynamics',
            field=models.ManyToManyField(blank=True, related_name='sentiment_logs', to='lookups.interactiondynamic'),
        ),
        migrations.AddField(
            model_name='socialenergylogdetail',
            name='factors',
            field=models.ManyToManyField(blank=True, related_name='social_energy_logs', to='lookups.socialenergyfactor'),
        ),
        migrations.AddConstraint(
            model_name='reflectionattachment',
            constraint=models.UniqueConstraint(fields=('reflection', 'media_asset'), name='unique_reflection_media_asset'),
        ),
        migrations.AddConstraint(
            model_name='reflectioncontact',
            constraint=models.UniqueConstraint(fields=('reflection', 'contact'), name='unique_reflection_contact'),
        ),
        migrations.RunPython(
            preserve_legacy_journals,
            migrations.RunPython.noop,
        ),
    ]
