# Generated by Django 6.0.3 on 2026-07-19 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_fact_source_item_id_fact_source_reflection_and_more'),
        ('events', '0005_eventchapter_eventchapterparticipant_eventmedia_and_more'),
        ('journals', '0005_carryforwardfactdraft_carryforwardobservationdraft_and_more'),
        ('lookups', '0019_normalize_episode_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='events.eventchapter'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='events.eventchapter'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'chapter', 'status', '-occurred_at'], name='log_owner_chap_status_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'chapter', 'status', '-occurred_at'], name='refl_owner_chap_stat_occ_idx'),
        ),
    ]
